// Extracts the Geist / Geist Mono woff2 subsets embedded in docs/design/fe1.html
// into web/public/fonts/ and generates web/src/styles/fonts.css with @font-face
// rules (unicode-range subsets) pointing at /fonts/<uuid>.woff2.
//
// Usage: npm run extract-fonts   (idempotent; safe to re-run)
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { gunzipSync } from "node:zlib";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const webRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const htmlPath = resolve(webRoot, "../docs/design/fe1.html");
const fontsDir = resolve(webRoot, "public/fonts");
const cssPath = resolve(webRoot, "src/styles/fonts.css");

const html = readFileSync(htmlPath, "utf8");
const manifestMatch = html.match(
  /<script type="__bundler\/manifest">([\s\S]*?)<\/script>/,
);
if (!manifestMatch) throw new Error("bundler manifest not found in fe1.html");
const manifest = JSON.parse(manifestMatch[1]);

mkdirSync(fontsDir, { recursive: true });
mkdirSync(dirname(cssPath), { recursive: true });

let written = 0;
for (const [id, entry] of Object.entries(manifest)) {
  if (entry.mime !== "font/woff2") continue;
  let raw = Buffer.from(entry.data, "base64");
  if (entry.compressed) raw = gunzipSync(raw);
  writeFileSync(resolve(fontsDir, `${id}.woff2`), raw);
  written++;
}

// Rewrite the @font-face rules from the bundle to point at /fonts/<uuid>.woff2.
const faces = html.match(/@font-face\s*\{[^}]*\}/g) ?? [];
const css = faces
  .map((rule) =>
    rule
      .replace(/\\n/g, "\n")
      .replace(/\\"/g, '"')
      .replace(/url\(("|')?([0-9a-f-]{36})("|')?\)/g, (_m, _q, uuid) => `url("/fonts/${uuid}.woff2")`)
      .replace(/[ \t]+/g, " ")
      .trim(),
  )
  .join("\n");
writeFileSync(
  cssPath,
  `/* Generated by scripts/extract-fonts.mjs from docs/design/fe1.html. Do not edit. */\n${css}\n`,
);

console.log(`extracted ${written} woff2 fonts, ${faces.length} @font-face rules`);
